/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void teacherSelectDraw(PApplet appc, GWinData data) { //_CODE_:teacherSelect:887505:
  appc.background(230);
} //_CODE_:teacherSelect:887505:

public void schattmanSelected(GButton source, GEvent event) { //_CODE_:schattmanButton:230753:
  println("schattmanButton - GButton >> GEvent." + event + " @ " + millis());
  currTeacher = schattman;
  reset();
  schattman.spewGibberish(); // comment this out later; for testing only
} //_CODE_:schattmanButton:230753:

public void bruzzeseSelected(GButton source, GEvent event) { //_CODE_:bruzzeseButton:915250:
  println("bruzzese - GButton >> GEvent." + event + " @ " + millis());
  currTeacher = bruzzese;
  reset();
  bruzzese.spewGibberish(); // comment later
} //_CODE_:bruzzeseButton:915250:

public void araujoSelected(GButton source, GEvent event) { //_CODE_:araujoButton:364774:
  println("araujoButton - GButton >> GEvent." + event + " @ " + millis());
  currTeacher = araujo;
  reset();
} //_CODE_:araujoButton:364774:

public void scullionSelected(GButton source, GEvent event) { //_CODE_:scullionButton:481099:
  println("scullionButton - GButton >> GEvent." + event + " @ " + millis());
  currTeacher = scullion;
  reset();
} //_CODE_:scullionButton:481099:

public void autogenerate(GButton source, GEvent event) { //_CODE_:autogenerateButton:613485:
  println("autogenerateButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:autogenerateButton:613485:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  teacherSelect = GWindow.getWindow(this, "Teacher Select Screen", 0, 0, 240, 180, JAVA2D);
  teacherSelect.noLoop();
  teacherSelect.setActionOnClose(G4P.KEEP_OPEN);
  teacherSelect.addDrawHandler(this, "teacherSelectDraw");
  schattmanButton = new GButton(teacherSelect, 24, 72, 80, 30);
  schattmanButton.setText("Schattman");
  schattmanButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  schattmanButton.addEventHandler(this, "schattmanSelected");
  bruzzeseButton = new GButton(teacherSelect, 136, 16, 80, 30);
  bruzzeseButton.setText("Bruzzese");
  bruzzeseButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  bruzzeseButton.addEventHandler(this, "bruzzeseSelected");
  araujoButton = new GButton(teacherSelect, 24, 16, 80, 30);
  araujoButton.setText("Araujo");
  araujoButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  araujoButton.addEventHandler(this, "araujoSelected");
  scullionButton = new GButton(teacherSelect, 136, 72, 80, 30);
  scullionButton.setText("Scullion (FR)");
  scullionButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  scullionButton.addEventHandler(this, "scullionSelected");
  label1 = new GLabel(teacherSelect, 47, 50, 150, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("CHOOSE YOUR VICTIM");
  label1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label1.setOpaque(false);
  togGroup1 = new GToggleGroup();
  togGroup2 = new GToggleGroup();
  autogenerateButton = new GButton(teacherSelect, 56, 120, 128, 40);
  autogenerateButton.setText("Generate something for me!");
  autogenerateButton.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  autogenerateButton.addEventHandler(this, "autogenerate");
  teacherSelect.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow teacherSelect;
GButton schattmanButton; 
GButton bruzzeseButton; 
GButton araujoButton; 
GButton scullionButton; 
GLabel label1; 
GToggleGroup togGroup1; 
GToggleGroup togGroup2; 
GButton autogenerateButton; 
